export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_PENDING = 'FETCH_LOCATIONS_PENDING';

export const FETCH_LOCATIONS_REJECTED = 'FETCH_LOCATIONS_REJECTED';
export const FETCH_LOCATIONS_FULFILLED = 'FETCH_LOCATIONS_FULFILLED';

export const SET_LOCATION = 'SET_LOCATION';
export const SET_RESTAURANT_NAME = 'SET_RESTAURANT_NAME';

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANTS_PENDING = 'FETCH_RESTAURANTS_PENDING';
export const FETCH_RESTAURANTS_REJECTED = 'FETCH_RESTAURANTS_REJECTED';
export const FETCH_RESTAURANTS_FULFILLED = 'FETCH_RESTAURANTS_FULFILLED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
export const FETCH_CATEGORIES_FULFILLED = 'FETCH_CATEGORIES_FULFILLED';

export const TOGGLE_FILTER_OPTION = 'TOGGLE_FILTER_OPTION';
export const TOGGLE_SEARCH_OPTION = 'TOGGLE_SEARCH_OPTION';

export const SET_FILTER_RATING_RANGE = 'SET_FILTER_RATING_RANGE';
export const SET_RATING_SORT_ORDER = 'SET_RATING_SORT_ORDER';
